repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
      - id: clang-format
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 7.3.1.1
    hooks:
      - id: buildifier
      - id: buildifier-lint
