name: Build plugins

on: push

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-22.04
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel build -c opt //:plugins
      - uses: actions/upload-artifact@v4
        with:
          name: plugins-${{ matrix.platform }}
          path: bazel-bin/plugins.tar.gz
