name: CI

on: push

jobs:
  ci:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.1
      - run: bazel build //...
      # - run: bazel test --test_output=errors //...
      - uses: actions/upload-artifact@v4
        with:
          name: plugins-${{ matrix.platform }}
          path: bazel-bin/plugins.tar.gz
